# this is root comment

# comment of field `a`
a = 0
# comment of field `b`
# optional, type: xxx, default: xxx
b = 0

# this is comment of `c`
# optional, type: i32 
# c = 1

# array, type: String
# d = [1]
d = []
